#This is Starter pipeline configuration for newcastle-helix
# Used to build, test and deploy using manual and parallel steps
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: atlassian/default-image:2

pipelines:
  default:
    - parallel:
      - step:
          name: 'Create .zip file'
          script:
            - echo "Create deployment .zip file..."
            - echo "Running tests goes here..."
      - step:
          name: 'Lint'
          script:
            - echo "Your linting goes here..."
      - step:
          name: 'Security scan'
          script:
            - echo "Your security scan goes here..."

    - step:
        name: 'Deployment to S3 Bitbucket'
        deployment: staging
        script:
          - echo "Your deployment to S3 bucket"
          - mkdir dist
          - zip -r dist/$BITBUCKET_REPO_SLUG.$(sed -e 's/\//./g' <<<$BITBUCKET_BRANCH).$BITBUCKET_BUILD_NUMBER.zip . -x *.git* "*.yml"          
          - pipe: atlassian/aws-s3-deploy:0.3.7
            variables:
              AWS_ACCESS_KEY_ID: 'AKIA5PVIBI226CN5NVX3'
              AWS_SECRET_ACCESS_KEY: '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'
              AWS_DEFAULT_REGION: 'eu-west-1'
              S3_BUCKET: 'motivait-dev-newcastle-helix'
              EXPIRES: '2022-10-01'
              LOCAL_PATH: 'dist'
              ACL: 'private'
#Add some comments here...
